### ISSUE TITLE
dear, have you done test with eorder(电子面单) function?

### ISSUE THREAD

**Issue by ghiewa** [menduo/kdniao_python#3]
I used your requests client, but run into to error with '验证数据签名失败'

have very rare expericence how to debug and make it work. sad!

**Comment by menduo** [comment]
@ghiewa Both Python 3.6.5 and Python 2.7.8 were tested successfully. What's env and parameters?

**Comment by ghiewa** [comment]
my test env, python 3.6.5

**Comment by ghiewa** [comment]
搞定了  是数据包里面有特殊字符
